import React, { useState, useEffect } from 'react';
import { Box, Grid } from '@mui/material';
import { collection, addDoc, onSnapshot, query, where, getDocs, doc, updateDoc, arrayUnion } from "firebase/firestore";
import { db } from '../../firebase';
import { useUserStore } from '../../userStore';
import ContactList from './ContactList';
import ChatHistory from './ChatHistory';
import Profile from './Profile';
import AddChatModal from './AddChatModal';

const Chat = () => {
  const { currentUser } = useUserStore();
    const [contacts, setContacts] = useState([]);
      const [selectedContact, setSelectedContact] = useState(null);
        const [messages, setMessages] = useState([]);
          const [filteredMessages, setFilteredMessages] = useState([]);
            const [selectedTag, setSelectedTag] = useState(null);
              const [isProfileOpen, setProfileOpen] = useState(false);
                const [isAddChatModalOpen, setAddChatModalOpen] = useState(false);

                  // Effect for fetching the contact list
                    useEffect(() => {
                        if (!currentUser?.uid) return;

                            const q = query(collection(db, "contacts"), where("participants", "array-contains", currentUser.uid));
                                const unsubscribe = onSnapshot(q, (snapshot) => {
                                      const chats = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
                                            setContacts(chats);
                                                });

                                                    return () => unsubscribe();
                                                      }, [currentUser?.uid]);

                                                        // Effect to update the selected contact when the contacts list changes
                                                          useEffect(() => {
   if (selectedContact) {
                                                                      const updatedContact = contacts.find(c => c.id === selectedContact.id);
                                                                              if (updatedContact) {
                                                                                          setSelectedContact(updatedContact);
                                                                                                  }
                                                                                                      } else if (contacts.length > 0) {
                                                                                                              setSelectedContact(contacts[0]);
                                                                                                                  }
                                                                                                                    }, [contacts]);

                                                                                                                      // Effect for fetching messages in real-time
                                                                                                                        useEffect(() => {
                                                                                                                            if (!selectedContact?.id) {
                                                                                                                                    setMessages([]);
                                                                                                                                            return;
                                                                                                                                                }

                                                                                                                                                    const contactDocRef = doc(db, "contacts", selectedContact.id);
                                                                                                                                                        const unsubscribe = onSnapshot(contactDocRef, (doc) => {
                                                                                                                                                                if (doc.exists()) {
                                                                                                                                                                            setMessages(doc.data().messages || []);
                                                                                                                                                                                    } else {
                                                                                                                                                                                                setMessages([]);
                                                                                                                                                                                                        }
                                                                                                                                                                                                            });

                                                                                                                                                                                                                return () => unsubscribe();
                                                                                                                                                                                                                  }, [selectedContact?.id]);

                                                                                                                                                                                                                    // Effect to filter messages based on the selected tag
                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                          if (selectedTag) {
                                                                                                                                                                                                                                setFilteredMessages(messages.filter(msg => msg.tag === selectedTag));
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                          setFilteredMessages(messages);
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                }, [selectedTag, messages]);


                                                                                                                                                                                                                                                  const handleSelectContact = (contact) => {
                                                                                                                                                                                                                                                      setSelectedContact(contact);
                                                                                                                                                                                                                                                          setProfileOpen(true);
                                                                                                                                                                                                                                                              setSelectedTag(null);
                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                  const handleToggleProfile = () => {
                                                                                                                                                                                                                                                                      setProfileOpen(!isProfileOpen);
                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                          const handleTagSelect = (tag) => {
                                                                                                                                                                                                                                                                              setSelectedTag(prevTag => prevTag === tag ? null : tag);
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                  const handleAddChat = async (chatData) => {
                                                                                                                                                                                                                                                                                      if (!chatData.isGroup) {
                                                                                                                                                                                                                                                                                            const otherUserId = chatData.participants.find(uid => uid !== currentUser.uid);
                                                                                                                                                                                                                                                                                                  const q = query(
                                                                                                                                                                                                                                                                                                          collection(db, "contacts"), 
                                                                                                                                                                                                                                                                                                                  where("isGroup", "==", false),
                                                                                                                                                                                                                                                                                                                          where("participants", "array-contains", currentUser.uid)
                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                      const querySnapshot = await getDocs(q);
                                                                                                                                                                                                                                                                                                                                            const existingChat = querySnapshot.docs.find(doc => doc.data().participants.includes(otherUserId));

                                                                                                                                                                                                                                                                                                                                                  if (existingChat) {
                                                                                                                                                                                                                                                                                                                                                          setSelectedContact({ id: existingChat.id, ...existingChat.data() });
                                                                                                                                                                                                                                                                                                                                                                  setAddChatModalOpen(false);
                                                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                              await addDoc(collection(db, "contacts"), { ...chatData, messages: [] });
                                                                                                                                                                                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                        console.error("Error adding document: ", e);
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                setAddChatModalOpen(false);
                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                    const handleSendMessage = async (messageData) => {
                                                                                                                                                                                                                                                                                                                                                                                                                        if (!selectedContact) return;

                                                                                                                                                                                                                                                                                                                                                                                                                            const contactDocRef = doc(db, "contacts", selectedContact.id);

                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                        await updateDoc(contactDocRef, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    messages: arrayUnion({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...messageData,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sentTime: new Date() 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error("Error sending message:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Box sx={{ flexGrow: 1, height: '100vh', overflow: 'hidden' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Grid container sx={{ height: '100%'}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Grid 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        item 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  xs={12} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sm={4} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      md={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sx={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRight: '1px solid #ddd', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: '100%', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    overflowY:'auto',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: { xs: selectedContact && !isProfileOpen ? 'none' : 'block', sm: 'block' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ContactList 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        contacts={contacts} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onSelectContact={handleSelectContact} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onAddChatClick={() => setAddChatModalOpen(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentUser={currentUser}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Grid 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        item 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  xs={12} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sm={8} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      md={isProfileOpen ? 6 : 9}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sx={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            height: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: { xs: selectedContact && !isProfileOpen ? 'block' : 'none', sm: 'block' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {selectedContact ? <ChatHistory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={selectedContact.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            contact={selectedContact}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        messages={filteredMessages} // Pass filtered messages
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onSendMessage={handleSendMessage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onToggleProfile={handleToggleProfile}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /> : <Box sx={{textAlign: 'center', mt: 4}}>Select a chat to start messaging</Box>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </Grid>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {isProfileOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <Grid 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     item 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   md={3} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 sx={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 height: '100%', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 borderLeft: '1px solid #ddd',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 display: { xs: 'block', sm: 'block' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {selectedContact && <Profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               contact={selectedContact}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   messages={messages} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onClose={handleToggleProfile}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           onTagSelect={handleTagSelect}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               selectedTag={selectedTag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {currentUser && <AddChatModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       open={isAddChatModalOpen}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               onClose={() => setAddChatModalOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onAddChat={handleAddChat}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               currentUser={currentUser}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           export default Chat;